// // app/layout.js
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";
// import AIChatWidget from "@/components/AIChatWidget";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col" suppressHydrationWarning={true}>
//         <Header />
//         <main className="flex-1 w-full flex flex-col">
//           {children}
//         </main>
//         <Footer />

//         <AIChatWidget/>
//       </body>
//     </html>
//   );
// }














// new version 
// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import AIChatWidget from "@/components/AIChatWidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ SEO + Social Meta Tags
export const metadata = {
  metadataBase: new URL("https://greenscape-app-frontend.vercel.app"),

  title: {
    default: "GreenScape — Live Green, Live Better",
    template: "%s | GreenScape",
  },

  description:
    "Shop premium plants, planters, and gardening essentials at GreenScape. Fast delivery across Pakistan. Live green, live better.",

  keywords: [
    "plants",
    "gardening",
    "indoor plants",
    "outdoor plants",
    "planters",
    "plant shop",
    "GreenScape",
    "Pakistan plants",
  ],

  authors: [{ name: "GreenScape" }],
  creator: "GreenScape",
  publisher: "GreenScape",

  // ✅ OpenGraph (Facebook, WhatsApp, LinkedIn, Slack, iMessage)
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://greenscape-app-frontend.vercel.app",
    siteName: "GreenScape",
    title: "GreenScape — Live Green, Live Better",
    description:
      "Shop premium plants, planters, and gardening essentials at GreenScape. Fast delivery across Pakistan.",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "GreenScape — Premium plants delivered to your door",
      },
    ],
  },

  // ✅ Twitter / X Card
  twitter: {
    card: "summary_large_image",
    title: "GreenScape — Live Green, Live Better",
    description:
      "Shop premium plants, planters, and gardening essentials at GreenScape. Fast delivery across Pakistan.",
    images: ["/og-image.jpg"],
    // creator: "@yourhandle",   // ← uncomment if you have a Twitter/X account
  },

  // ✅ Icons
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },

  // ✅ Robots (let search engines index)
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#2B7A4B",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning={true}>
        <Header />
        <main className="flex-1 w-full flex flex-col">
          {children}
        </main>
        <Footer />

        <AIChatWidget />
      </body>
    </html>
  );
}